'use client';

import React, { useState } from 'react';
import { Upload, Check, Loader2 } from 'lucide-react';

interface OrgDetails {
  id: string;
  name: string;
  logoUrl: string | null;
  brandColor: string | null;
  customFooter: string | null;
}

export function BrandingForm({ initialOrg }: { initialOrg: OrgDetails }) {
  const [logoUrl, setLogoUrl] = useState(initialOrg.logoUrl || '');
  const [brandColor, setBrandColor] = useState(initialOrg.brandColor || '#3b82f6');
  const [customFooter, setCustomFooter] = useState(initialOrg.customFooter || '');
  const [uploading, setUploading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  // Logo file upload handler
  const handleLogoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate type (images only)
    if (!file.type.startsWith('image/')) {
      setMessage({ type: 'error', text: 'Please select an image file (PNG, JPG, SVG).' });
      return;
    }

    setUploading(true);
    setMessage(null);

    const formData = new FormData();
    formData.append('file', file);

    try {
      const res = await fetch('/api/settings/branding/logo', {
        method: 'POST',
        body: formData,
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Upload failed');
      }

      setLogoUrl(data.logoUrl);
      setMessage({ type: 'success', text: 'Logo uploaded successfully.' });
    } catch (err: unknown) {
      console.error(err);
      setMessage({ type: 'error', text: err instanceof Error ? err.message : 'Failed to upload logo.' });
    } finally {
      setUploading(false);
    }
  };

  // Submit branding configurations
  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setMessage(null);

    try {
      const res = await fetch('/api/settings/branding', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          logoUrl,
          brandColor,
          customFooter,
        }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Failed to save configurations');
      }

      setMessage({ type: 'success', text: 'Branding preferences saved successfully.' });
    } catch (err: unknown) {
      console.error(err);
      setMessage({ type: 'error', text: err instanceof Error ? err.message : 'Failed to save changes.' });
    } finally {
      setSaving(false);
    }
  };

  return (
    <form onSubmit={handleSave} className="glass-panel rounded-lg p-6 space-y-6">
      <div>
        <h2 className="text-xl font-semibold text-white">Custom Report Branding</h2>
        <p className="mt-1 text-sm text-zinc-400">
          Personalize the look and feel of client PDF reports generated by Maintly.
        </p>
      </div>

      {message && (
        <div
          className={`p-4 rounded-md text-sm ${
            message.type === 'success'
              ? 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-300'
              : 'bg-rose-500/10 border border-rose-500/20 text-rose-300'
          }`}
        >
          {message.text}
        </div>
      )}

      {/* Logo upload field */}
      <div className="space-y-2">
        <label className="block text-sm font-medium text-zinc-300">Agency Logo</label>
        <div className="flex items-center gap-6">
          <div className="size-20 rounded-md border border-white/10 bg-white/[0.02] flex items-center justify-center overflow-hidden shrink-0">
            {logoUrl ? (
              <img src={logoUrl} alt="Agency Logo" className="object-contain max-w-full max-h-full p-1" />
            ) : (
              <span className="text-xs text-zinc-600 font-mono uppercase">no logo</span>
            )}
          </div>
          <div className="relative">
            <input
              type="file"
              id="logo-input"
              accept="image/*"
              className="sr-only"
              onChange={handleLogoUpload}
              disabled={uploading || saving}
            />
            <label
              htmlFor="logo-input"
              className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-md border border-white/10 bg-white/5 hover:bg-white/10 text-white cursor-pointer select-none transition-colors ${
                uploading ? 'opacity-50 pointer-events-none' : ''
              }`}
            >
              {uploading ? (
                <>
                  <Loader2 className="size-4 animate-spin text-zinc-400" />
                  Uploading...
                </>
              ) : (
                <>
                  <Upload className="size-4 text-cyan-300" />
                  Upload image
                </>
              )}
            </label>
            <p className="mt-1.5 text-xs text-zinc-500">Supports PNG, JPG, or SVG. Square or wide ratios.</p>
          </div>
        </div>
      </div>

      {/* Primary Brand Color Selection */}
      <div className="space-y-2">
        <label className="block text-sm font-medium text-zinc-300">Primary Theme Color</label>
        <div className="flex items-center gap-4">
          <input
            type="color"
            value={brandColor}
            onChange={(e) => setBrandColor(e.target.value)}
            disabled={saving}
            className="size-10 bg-transparent border-0 rounded cursor-pointer shrink-0"
          />
          <input
            type="text"
            value={brandColor}
            onChange={(e) => setBrandColor(e.target.value)}
            placeholder="#3b82f6"
            disabled={saving}
            className="w-32 rounded-md border border-white/10 bg-white/[0.02] px-3 py-2 text-sm text-white placeholder-zinc-600 focus:outline-none focus:ring-1 focus:ring-cyan-400"
          />
          <p className="text-xs text-zinc-500">
            Accent color applied to PDF headers, boundaries, and highlights.
          </p>
        </div>
      </div>

      {/* Custom footer text */}
      <div className="space-y-2">
        <label htmlFor="footer-input" className="block text-sm font-medium text-zinc-300">
          Custom Report Footer
        </label>
        <textarea
          id="footer-input"
          value={customFooter}
          onChange={(e) => setCustomFooter(e.target.value)}
          placeholder={`e.g. For questions about your website care plan, email support@youragency.com.`}
          rows={3}
          disabled={saving}
          className="w-full rounded-md border border-white/10 bg-white/[0.02] px-3 py-2 text-sm text-white placeholder-zinc-600 focus:outline-none focus:ring-1 focus:ring-cyan-400"
        />
        <p className="text-xs text-zinc-500">
          Appears at the bottom of each page of generated monthly reports.
        </p>
      </div>

      {/* Actions */}
      <div className="flex justify-end pt-4 border-t border-white/5">
        <button
          type="submit"
          disabled={saving || uploading}
          className="flex items-center gap-2 rounded-md bg-cyan-400 px-4 py-2 text-sm font-semibold text-[#080c14] hover:bg-cyan-300 transition-colors disabled:opacity-50"
        >
          {saving ? (
            <>
              <Loader2 className="size-4 animate-spin text-[#080c14]" />
              Saving...
            </>
          ) : (
            <>
              <Check className="size-4 text-[#080c14]" />
              Save branding
            </>
          )}
        </button>
      </div>
    </form>
  );
}
